# Generated by Django 5.2.8 on 2025-11-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_Name', models.CharField(blank=True, max_length=15, null=True)),
                ('Category_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Duration', models.IntegerField(blank=True, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Featured', models.BooleanField(default=False)),
                ('Status', models.CharField(blank=True, max_length=10, null=True)),
                ('Service_Image', models.ImageField(blank=True, null=True, upload_to='Service')),
            ],
        ),
    ]
