# Generated by Django 5.2.8 on 2025-11-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0002_servicedb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorydb',
            name='Status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
    ]
