# Generated by Django 5.2.8 on 2025-11-26 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0003_alter_categorydb_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedb',
            name='Category_Name',
        ),
        migrations.AddField(
            model_name='servicedb',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin_App.categorydb'),
        ),
        migrations.AlterField(
            model_name='categorydb',
            name='Status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
    ]
