# Generated by Django 5.2.8 on 2025-11-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0004_remove_servicedb_category_name_servicedb_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedb',
            name='Featured',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
