# Generated by Django 5.2.8 on 2025-11-28 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0005_alter_servicedb_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedb',
            name='Featured',
        ),
    ]
