# Generated by Django 5.2.8 on 2025-12-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0006_remove_servicedb_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staffdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Staff_Name', models.CharField(blank=True, max_length=15, null=True)),
                ('Role', models.CharField(blank=True, max_length=50, null=True)),
                ('Work_category', models.CharField(blank=True, max_length=50, null=True)),
                ('Services', models.TextField(blank=True, null=True)),
                ('Phone', models.CharField(blank=True, max_length=15, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Experience', models.CharField(blank=True, max_length=50, null=True)),
                ('Salary', models.IntegerField(blank=True, null=True)),
                ('Staff_image', models.ImageField(blank=True, null=True, upload_to='Staff')),
            ],
        ),
    ]
