# Generated by Django 5.2.8 on 2025-12-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointmentdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Phone', models.CharField(blank=True, max_length=10, null=True)),
                ('Category', models.CharField(blank=True, max_length=100, null=True)),
                ('Service', models.CharField(blank=True, max_length=100, null=True)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('staff_level', models.CharField(choices=[('gold', 'Gold Level'), ('silver', 'Silver Level'), ('bronze', 'Bronze Level')], max_length=20)),
                ('assigned_staff', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
